markdown:  kramdown
baseurl:   /ShenipsitStriders.github.io
exclude:   [README.md, .gitignore]
permalink: date
future: true
excerpt_separator: "\n"
collections:
  events:
    permalink: /:path:output_ext
    output: true
  posts:
    permalink: /:year/:month/:day/:title:output_ext