markdown:   kramdown
title:      Shenipsit Striders
description: Trail Running in New England and Beyond
url:        http://shenipsitstriders.org
baseurl:    ""
webmaster_verifications:
  google:   CZUy5fl_f1Z_COHVXxBzNJ_YGftSI2bJR4ay4PXMjLY
logo:       /images/Shenipsit-Striders-greenonmango.jpg
twitter:
  username: ShenipsitStrdrs
  card: summary
facebook:
  publisher: https://www.facebook.com/groups/shenipsitstriders/
exclude:   
  - README.md
  - .git
  - .gitignore
  - .gitattributes
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - compileanddeploy.sh
  - config.sh
  - config.sh.example
  - prodconfig.yml
  - _club-races/event_template.md
permalink: date
future: true
collections:
  fun-runs:
    output: true
  club-races:
    output: true
  posts:
    permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  