markdown:  kramdown
baseurl:   /ShenipsitStriders.github.io
exclude:   ["README.md", ".gitignore", ".gitattributes", "compileanddeploy.sh", "config.sh", "config.sh.example", "prodconfig.yml"]
permalink: date
